// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using RickAndMorty.Infrastracture.Data;

#nullable disable

namespace RickAndMorty.Infrastracture.Migrations
{
	[DbContext(typeof(RickAndMortyContext))]
    [Migration("20230316225804_ModelRevisions")]
    partial class ModelRevisions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);
#pragma warning restore 612, 618
        }
    }
}
